---
title: "tidytuesday 2024-04-23"
format: html
editor: visual
---
```{r}
if (!require(pacman)) install.packages("pacman")
pacman::p_load(
  gganimate,
  ggtext,
  showtext,
  here,
  tidyverse,
  tidytuesdayR,
  png,
  gifski
)
```
# ✍️ fonts and palettes
```{r}
txt <- "white"
bg <- "grey20"

font_add_google("Fira Code", "fira")
showtext_auto()

ft <- "fira"
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2024-04-23')
```

```{r}
data <- tuesdata$outer_space_objects
```

```{r}
data |> glimpse()
```

```{r}
data |> 
  filter(Entity != "World") |> 
  group_by(Entity) |> 
  summarise(n = sum(num_objects, na.rm = TRUE)) |> 
  ggplot(aes(x = fct_reorder(Entity, n), y = n)) +
  geom_col() +
  coord_flip()
```

```{r}
top_entities <- data |> 
  filter(Entity != "World") |> 
  group_by(entity = fct_lump_n(Entity, w = num_objects, n = 10, ties.method = "first")) |> 
  summarise(n = sum(num_objects, na.rm = TRUE)) |> 
  filter(entity != "Other") |> 
  arrange(desc(n)) |> 
  pull(entity)
```

```{r}
data |> 
  filter(Entity %in% top_entities) |> 
  complete(Entity, Year) |> 
  group_by(
    entity = Entity,
    year = Year) |> 
  summarise(
    objects = sum(num_objects, na.rm = TRUE)
  ) |> 
  mutate(total_objects = cumsum(objects)) |>
  arrange(year, desc(total_objects)) |> 
  group_by(year) |> 
  mutate(rank = row_number(desc(total_objects))) |> 
  arrange(year, rank)
```

```{r}
p <- data |> 
  filter(Entity %in% top_entities) |> 
  complete(Entity, Year) |> 
  group_by(
    entity = Entity,
    year = Year) |> 
  summarise(
    objects = sum(num_objects, na.rm = TRUE)
  ) |> 
  mutate(total_objects = cumsum(objects)) |>
  arrange(year, desc(total_objects)) |> 
  group_by(year) |> 
  mutate(rank = row_number(desc(total_objects))) |> 
  arrange(year, rank) |> 
  ggplot() +
  geom_col(aes(x = rank, y = total_objects, fill = entity)) +
  geom_text(aes(x = rank, y = -100, label = entity), hjust = 1, color = txt) +
  geom_text(aes(x = rank, y = total_objects + 200, label = as.character(total_objects)), hjust = 0, color = txt) +
  coord_flip(clip = "off", expand = FALSE) +
  labs(
    title = "Travesía Cósmica: La Carrera Anual al Espacio",
    subtitle = 'Año: {closest_state}',
    x = "", 
    y = "Número de objetos",
    caption = "Desde Sputnik hasta SpaceX, contempla el fascinante baile de la conquista cósmica en esta animada competencia de barras.") +
  scale_y_continuous(
    labels = scales::comma,
    breaks = seq(0, 10000, 1000)
  ) +
  scale_x_reverse() +
  transition_states(year, transition_length = 4, state_length = 1, wrap = FALSE) +
  enter_fade() + 
  exit_fade() +
  theme_void() +
  theme(
    # text = element_text(family = ft, size = 14, lineheight = 0.1, colour = txt),
    text = element_text(size = 14, lineheight = 0.1, colour = txt),
    plot.background = element_rect(fill = bg, colour = bg),
    # plot.title = element_textbox_simple(colour = txt, hjust = 0.05, margin = margin(t = 10, b = 10), size = 18, face = "bold", family = ft),
    plot.title = element_textbox_simple(colour = txt, hjust = 0.05, margin = margin(t = 10, b = 10), size = 18, face = "bold"),
    plot.subtitle = element_markdown(colour = txt, hjust = 0.05, margin = margin(t = 10, b = 20)),
    plot.caption = element_textbox_simple(colour = txt, hjust = 0.5, margin = margin(t = 10)),
    plot.margin = margin(b = 20, t = 10, r = 50, l = 150),
    axis.text = element_text(colour = txt, size = 10),
    axis.text.y = element_blank(),
    legend.position = "none"
  )

animate(p, fps = 30, duration = 30, width = 800, height = 600)


```


```{r}
anim_save(here("2024-04-23_objects-launched-into-space","plot.gif"), animation = last_animation())
```

