---
title: "Video Games and Sliced"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
theme_set(theme_light())
```

# Load the weekly Data

Download the weekly data and make available in the `tt` object

```{r}

tt <- tt_load("2021-03-16")

tibble(date = seq(as.Date("2020-01-01"), as.Date("2020-12-31"), 1)) %>%
  mutate(month_number = month(date))

games <- tt$games %>% 
  mutate(avg_peak_perc = parse_number(avg_peak_perc) / 100) %>% 
  mutate(date = ymd(paste(year,month, 1))) %>% 
  filter(date > min(date)) %>% 
  mutate(month = fct_reorder(month, month(date)))

```

```{r}
games %>% 
  count(date) %>% 
  ggplot(aes(date, n)) +
  geom_col()

games %>% 
  group_by(date) %>% 
  summarize(median_avg = median(avg)) %>% 
  ggplot(aes(date, median_avg)) +
  geom_line() +
  expand_limits(y = 0) +
  labs(x = "Month",
       y = "Median popularity of a game on Steam")

summarize_games <- function(tbl) {
  tbl %>% 
    summarize(median_avg = median(avg),
              median_peak = median(peak))
}

games %>% 
  filter(date < "2020-01-01") %>% 
  group_by(month) %>% 
  summarize_games() %>% 
  ggplot(aes(month, median_avg)) +
  geom_line(group = 1) +
  expand_limits(y = 0) +
  labs(x = "Month of Year",
       y = "Median popularity of a game on Steam",
       title = "Seasonal trend in Steam games",
       subtitle = "From 2012-2019")

games %>% 
  filter(date < "2020-01-01") %>% 
  group_by(year, month) %>% 
  summarize_games() %>% 
  ggplot(aes(month, median_avg)) +
  geom_line(aes(color = factor(year), group = year)) +
  expand_limits(y = 0) +
  labs(x = "Month of Year",
       y = "Median popularity of a game on Steam",
       title = "Seasonal trend in Steam games",
       subtitle = "From 2012-2019",
       color = "year")

games %>% 
  group_by(date) %>% 
  summarize_games() %>% 
  ggplot(aes(date, median_peak)) +
  geom_line() +
  expand_limits(y = 0)
```

Distribution of game popularity

```{r}
games %>% 
  filter(date == max(date)) %>% 
  ggplot(aes(avg)) +
  geom_histogram() +
  scale_x_log10(labels = comma,
                breaks = 10 ^ seq(0, 5)) +
  labs(x = "Average # of players across Feb 2021 ")

games %>%
  filter(avg >= 100) %>% 
  filter(date == max(date)) %>%
    arrange(avg_peak_perc)
  
games %>% 
  filter(date == max(date)) %>% 
  arrange(desc(avg))
```

