---
title: "2020-03-17_the_office"
format: html
---

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  ggrepel,
  tidyverse,
  tidytext,
  schrute
)

theme_set(theme_light())
```

```{r}
office_transcripts <- as_tibble(theoffice) %>% 
  mutate(season = as.integer(season),
         episode = as.integer(episode)) %>% 
  mutate(character = str_remove_all(character, '"|\\(|\\)'))

office_ratings <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv')
```

```{r}
office_ratings %>% 
  group_by(season) %>% 
  summarise(avg_rating = mean(imdb_rating)) %>% 
  ggplot(aes(season, avg_rating)) +
  geom_line() +
  scale_x_continuous(breaks = 1:9)


office_ratings %>% 
  mutate(title = fct_inorder(title),
         episode_number = row_number()) %>% 
  ggplot(aes(episode_number, imdb_rating)) +
  geom_line() +
  geom_smooth() +
  geom_point(aes(color = factor(season), size = total_votes)) +
  geom_text(aes(label = title), check_overlap = TRUE, hjust = 1) +
  expand_limits(x = -10) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "none") +
  labs(x = "Episode number",
       y = "IMDB Rating",
       title = "Popularity of The Office episodes over time",
       subtitle = "Color represents season, size represent # of ratings")
```
```{r}
office_ratings %>% 
  arrange(desc(imdb_rating)) %>% 
  mutate(title = paste0(season,".", episode, " ", title),
         title = fct_reorder(title, imdb_rating)) %>% 
  head(20) %>% 
  ggplot(aes(title, imdb_rating, color = factor(season), size = total_votes)) +
  geom_point() +
  coord_flip() +
  labs(
    color = "Season",
    title = "Most popular episodes of The Office"
  )
```

### Transcripts
```{r}
blacklist <- c("yeah", "hey", "uh", "gonna", "um", "god", "day", "guys", "call")
blacklist_characters <- c("Everyone", "All", "Both", "Guy", "Girl", "Man", "Woman", "Group")
transcript_words <- office_transcripts %>% 
  group_by(character) %>% 
  filter(n() >= 100,
         n_distinct(episode_name) > 2) %>% 
  ungroup() %>% 
  select(-text_w_direction) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word %in% blacklist,
         !character %in% blacklist_characters)

character_tf_idf <- transcript_words %>% 
  add_count(word) %>% 
  filter(n >= 20) %>% 
  count(word, character) %>% 
  bind_tf_idf(word, character, n) %>% 
  arrange(desc(tf_idf))
```

```{r}
character_tf_idf %>% 
  filter(character %in% c("Dwight", "Jim", "Michael", "Darryl", "Jan", "Holly")) %>% 
  group_by(character) %>% 
  top_n(20, tf_idf) %>% 
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, character)) %>% 
  ggplot(aes(word, tf_idf)) +
  geom_col() +
  coord_flip() +
  scale_x_reordered() +
  facet_wrap(~ character, scales = "free") +
  labs(x = "",
       y = "TF-IDF of character-word pairs")
```

